Traceback (most recent call last):
  File "/home/natalie/Dokumente/Datenjournalismus in Python/Code/.venv/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/natalie/Dokumente/Datenjournalismus in Python/Code/.venv/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/natalie/Dokumente/Datenjournalismus in Python/Code/.venv/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/natalie/Dokumente/Datenjournalismus in Python/Code/.venv/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/natalie/Dokumente/Datenjournalismus in Python/Code/.venv/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/natalie/Dokumente/Datenjournalismus in Python/Code/.venv/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
url = 'https://www.mdr.de/nachrichten/sachsen/index.html'
response = requests.get(url)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m url [38;5;241m=[39m [38;5;124m'[39m[38;5;124mhttps://www.mdr.de/nachrichten/sachsen/index.html[39m[38;5;124m'[39m
[0;32m----> 2[0m response [38;5;241m=[39m [43mrequests[49m[38;5;241m.[39mget(url)

[0;31mNameError[0m: name 'requests' is not defined

