Traceback (most recent call last):
  File "/home/natalie-widmann/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/natalie-widmann/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/natalie-widmann/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/natalie-widmann/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/natalie-widmann/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/natalie-widmann/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/natalie-widmann/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
pd.set_option('display.float_format', '{:.2f}'.format)

data_url = "https://data.humdata.org/dataset/74163686-a029-4e27-8fbf-c5bfcd13f953/resource/c5ce40d6-07b1-4f36-955a-d6196436ff6b/download/emdat-country-profiles_2024_11_25.xlsx"
data = pd.read_excel(data_url, engine="openpyxl")
data
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mHTTPError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 5[0m
[1;32m      2[0m pd[38;5;241m.[39mset_option([38;5;124m'[39m[38;5;124mdisplay.float_format[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;132;01m{:.2f}[39;00m[38;5;124m'[39m[38;5;241m.[39mformat)
[1;32m      4[0m data_url [38;5;241m=[39m [38;5;124m"[39m[38;5;124mhttps://data.humdata.org/dataset/74163686-a029-4e27-8fbf-c5bfcd13f953/resource/c5ce40d6-07b1-4f36-955a-d6196436ff6b/download/emdat-country-profiles_2024_11_25.xlsx[39m[38;5;124m"[39m
[0;32m----> 5[0m data [38;5;241m=[39m pd[38;5;241m.[39mread_excel(data_url, engine[38;5;241m=[39m[38;5;124m"[39m[38;5;124mopenpyxl[39m[38;5;124m"[39m)
[1;32m      6[0m data

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/io/excel/_base.py:495[0m, in [0;36mread_excel[0;34m(io, sheet_name, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, date_format, thousands, decimal, comment, skipfooter, storage_options, dtype_backend, engine_kwargs)[0m
[1;32m    493[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(io, ExcelFile):
[1;32m    494[0m     should_close [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[0;32m--> 495[0m     io [38;5;241m=[39m ExcelFile(
[1;32m    496[0m         io,
[1;32m    497[0m         storage_options[38;5;241m=[39mstorage_options,
[1;32m    498[0m         engine[38;5;241m=[39mengine,
[1;32m    499[0m         engine_kwargs[38;5;241m=[39mengine_kwargs,
[1;32m    500[0m     )
[1;32m    501[0m [38;5;28;01melif[39;00m engine [38;5;129;01mand[39;00m engine [38;5;241m!=[39m io[38;5;241m.[39mengine:
[1;32m    502[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    503[0m         [38;5;124m"[39m[38;5;124mEngine should not be specified when passing [39m[38;5;124m"[39m
[1;32m    504[0m         [38;5;124m"[39m[38;5;124man ExcelFile - ExcelFile already has the engine set[39m[38;5;124m"[39m
[1;32m    505[0m     )

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/io/excel/_base.py:1567[0m, in [0;36mExcelFile.__init__[0;34m(self, path_or_buffer, engine, storage_options, engine_kwargs)[0m
[1;32m   1564[0m [38;5;28mself[39m[38;5;241m.[39mengine [38;5;241m=[39m engine
[1;32m   1565[0m [38;5;28mself[39m[38;5;241m.[39mstorage_options [38;5;241m=[39m storage_options
[0;32m-> 1567[0m [38;5;28mself[39m[38;5;241m.[39m_reader [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_engines[engine](
[1;32m   1568[0m     [38;5;28mself[39m[38;5;241m.[39m_io,
[1;32m   1569[0m     storage_options[38;5;241m=[39mstorage_options,
[1;32m   1570[0m     engine_kwargs[38;5;241m=[39mengine_kwargs,
[1;32m   1571[0m )

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/io/excel/_openpyxl.py:553[0m, in [0;36mOpenpyxlReader.__init__[0;34m(self, filepath_or_buffer, storage_options, engine_kwargs)[0m
[1;32m    541[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m    542[0m [38;5;124;03mReader using openpyxl engine.[39;00m
[1;32m    543[0m 
[0;32m   (...)[0m
[1;32m    550[0m [38;5;124;03m    Arbitrary keyword arguments passed to excel engine.[39;00m
[1;32m    551[0m [38;5;124;03m"""[39;00m
[1;32m    552[0m import_optional_dependency([38;5;124m"[39m[38;5;124mopenpyxl[39m[38;5;124m"[39m)
[0;32m--> 553[0m [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m(
[1;32m    554[0m     filepath_or_buffer,
[1;32m    555[0m     storage_options[38;5;241m=[39mstorage_options,
[1;32m    556[0m     engine_kwargs[38;5;241m=[39mengine_kwargs,
[1;32m    557[0m )

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/io/excel/_base.py:563[0m, in [0;36mBaseExcelReader.__init__[0;34m(self, filepath_or_buffer, storage_options, engine_kwargs)[0m
[1;32m    559[0m [38;5;28mself[39m[38;5;241m.[39mhandles [38;5;241m=[39m IOHandles(
[1;32m    560[0m     handle[38;5;241m=[39mfilepath_or_buffer, compression[38;5;241m=[39m{[38;5;124m"[39m[38;5;124mmethod[39m[38;5;124m"[39m: [38;5;28;01mNone[39;00m}
[1;32m    561[0m )
[1;32m    562[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(filepath_or_buffer, (ExcelFile, [38;5;28mself[39m[38;5;241m.[39m_workbook_class)):
[0;32m--> 563[0m     [38;5;28mself[39m[38;5;241m.[39mhandles [38;5;241m=[39m get_handle(
[1;32m    564[0m         filepath_or_buffer, [38;5;124m"[39m[38;5;124mrb[39m[38;5;124m"[39m, storage_options[38;5;241m=[39mstorage_options, is_text[38;5;241m=[39m[38;5;28;01mFalse[39;00m
[1;32m    565[0m     )
[1;32m    567[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m([38;5;28mself[39m[38;5;241m.[39mhandles[38;5;241m.[39mhandle, [38;5;28mself[39m[38;5;241m.[39m_workbook_class):
[1;32m    568[0m     [38;5;28mself[39m[38;5;241m.[39mbook [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mhandles[38;5;241m.[39mhandle

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/io/common.py:728[0m, in [0;36mget_handle[0;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[1;32m    725[0m     codecs[38;5;241m.[39mlookup_error(errors)
[1;32m    727[0m [38;5;66;03m# open URLs[39;00m
[0;32m--> 728[0m ioargs [38;5;241m=[39m _get_filepath_or_buffer(
[1;32m    729[0m     path_or_buf,
[1;32m    730[0m     encoding[38;5;241m=[39mencoding,
[1;32m    731[0m     compression[38;5;241m=[39mcompression,
[1;32m    732[0m     mode[38;5;241m=[39mmode,
[1;32m    733[0m     storage_options[38;5;241m=[39mstorage_options,
[1;32m    734[0m )
[1;32m    736[0m handle [38;5;241m=[39m ioargs[38;5;241m.[39mfilepath_or_buffer
[1;32m    737[0m handles: [38;5;28mlist[39m[BaseBuffer]

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/io/common.py:384[0m, in [0;36m_get_filepath_or_buffer[0;34m(filepath_or_buffer, encoding, compression, mode, storage_options)[0m
[1;32m    382[0m [38;5;66;03m# assuming storage_options is to be interpreted as headers[39;00m
[1;32m    383[0m req_info [38;5;241m=[39m urllib[38;5;241m.[39mrequest[38;5;241m.[39mRequest(filepath_or_buffer, headers[38;5;241m=[39mstorage_options)
[0;32m--> 384[0m [38;5;28;01mwith[39;00m urlopen(req_info) [38;5;28;01mas[39;00m req:
[1;32m    385[0m     content_encoding [38;5;241m=[39m req[38;5;241m.[39mheaders[38;5;241m.[39mget([38;5;124m"[39m[38;5;124mContent-Encoding[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m)
[1;32m    386[0m     [38;5;28;01mif[39;00m content_encoding [38;5;241m==[39m [38;5;124m"[39m[38;5;124mgzip[39m[38;5;124m"[39m:
[1;32m    387[0m         [38;5;66;03m# Override compression based on Content-Encoding header[39;00m

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/io/common.py:289[0m, in [0;36murlopen[0;34m(*args, **kwargs)[0m
[1;32m    283[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m    284[0m [38;5;124;03mLazy-import wrapper for stdlib urlopen, as that imports a big chunk of[39;00m
[1;32m    285[0m [38;5;124;03mthe stdlib.[39;00m
[1;32m    286[0m [38;5;124;03m"""[39;00m
[1;32m    287[0m [38;5;28;01mimport[39;00m [38;5;21;01murllib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mrequest[39;00m
[0;32m--> 289[0m [38;5;28;01mreturn[39;00m urllib[38;5;241m.[39mrequest[38;5;241m.[39murlopen([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [0;32m~/anaconda3/lib/python3.11/urllib/request.py:216[0m, in [0;36murlopen[0;34m(url, data, timeout, cafile, capath, cadefault, context)[0m
[1;32m    214[0m [38;5;28;01melse[39;00m:
[1;32m    215[0m     opener [38;5;241m=[39m _opener
[0;32m--> 216[0m [38;5;28;01mreturn[39;00m opener[38;5;241m.[39mopen(url, data, timeout)

File [0;32m~/anaconda3/lib/python3.11/urllib/request.py:525[0m, in [0;36mOpenerDirector.open[0;34m(self, fullurl, data, timeout)[0m
[1;32m    523[0m [38;5;28;01mfor[39;00m processor [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mprocess_response[38;5;241m.[39mget(protocol, []):
[1;32m    524[0m     meth [38;5;241m=[39m [38;5;28mgetattr[39m(processor, meth_name)
[0;32m--> 525[0m     response [38;5;241m=[39m meth(req, response)
[1;32m    527[0m [38;5;28;01mreturn[39;00m response

File [0;32m~/anaconda3/lib/python3.11/urllib/request.py:634[0m, in [0;36mHTTPErrorProcessor.http_response[0;34m(self, request, response)[0m
[1;32m    631[0m [38;5;66;03m# According to RFC 2616, "2xx" code indicates that the client's[39;00m
[1;32m    632[0m [38;5;66;03m# request was successfully received, understood, and accepted.[39;00m
[1;32m    633[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m ([38;5;241m200[39m [38;5;241m<[39m[38;5;241m=[39m code [38;5;241m<[39m [38;5;241m300[39m):
[0;32m--> 634[0m     response [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mparent[38;5;241m.[39merror(
[1;32m    635[0m         [38;5;124m'[39m[38;5;124mhttp[39m[38;5;124m'[39m, request, response, code, msg, hdrs)
[1;32m    637[0m [38;5;28;01mreturn[39;00m response

File [0;32m~/anaconda3/lib/python3.11/urllib/request.py:557[0m, in [0;36mOpenerDirector.error[0;34m(self, proto, *args)[0m
[1;32m    555[0m     http_err [38;5;241m=[39m [38;5;241m0[39m
[1;32m    556[0m args [38;5;241m=[39m ([38;5;28mdict[39m, proto, meth_name) [38;5;241m+[39m args
[0;32m--> 557[0m result [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_call_chain([38;5;241m*[39margs)
[1;32m    558[0m [38;5;28;01mif[39;00m result:
[1;32m    559[0m     [38;5;28;01mreturn[39;00m result

File [0;32m~/anaconda3/lib/python3.11/urllib/request.py:496[0m, in [0;36mOpenerDirector._call_chain[0;34m(self, chain, kind, meth_name, *args)[0m
[1;32m    494[0m [38;5;28;01mfor[39;00m handler [38;5;129;01min[39;00m handlers:
[1;32m    495[0m     func [38;5;241m=[39m [38;5;28mgetattr[39m(handler, meth_name)
[0;32m--> 496[0m     result [38;5;241m=[39m func([38;5;241m*[39margs)
[1;32m    497[0m     [38;5;28;01mif[39;00m result [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    498[0m         [38;5;28;01mreturn[39;00m result

File [0;32m~/anaconda3/lib/python3.11/urllib/request.py:749[0m, in [0;36mHTTPRedirectHandler.http_error_302[0;34m(self, req, fp, code, msg, headers)[0m
[1;32m    746[0m fp[38;5;241m.[39mread()
[1;32m    747[0m fp[38;5;241m.[39mclose()
[0;32m--> 749[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mparent[38;5;241m.[39mopen(new, timeout[38;5;241m=[39mreq[38;5;241m.[39mtimeout)

File [0;32m~/anaconda3/lib/python3.11/urllib/request.py:525[0m, in [0;36mOpenerDirector.open[0;34m(self, fullurl, data, timeout)[0m
[1;32m    523[0m [38;5;28;01mfor[39;00m processor [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mprocess_response[38;5;241m.[39mget(protocol, []):
[1;32m    524[0m     meth [38;5;241m=[39m [38;5;28mgetattr[39m(processor, meth_name)
[0;32m--> 525[0m     response [38;5;241m=[39m meth(req, response)
[1;32m    527[0m [38;5;28;01mreturn[39;00m response

File [0;32m~/anaconda3/lib/python3.11/urllib/request.py:634[0m, in [0;36mHTTPErrorProcessor.http_response[0;34m(self, request, response)[0m
[1;32m    631[0m [38;5;66;03m# According to RFC 2616, "2xx" code indicates that the client's[39;00m
[1;32m    632[0m [38;5;66;03m# request was successfully received, understood, and accepted.[39;00m
[1;32m    633[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m ([38;5;241m200[39m [38;5;241m<[39m[38;5;241m=[39m code [38;5;241m<[39m [38;5;241m300[39m):
[0;32m--> 634[0m     response [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mparent[38;5;241m.[39merror(
[1;32m    635[0m         [38;5;124m'[39m[38;5;124mhttp[39m[38;5;124m'[39m, request, response, code, msg, hdrs)
[1;32m    637[0m [38;5;28;01mreturn[39;00m response

File [0;32m~/anaconda3/lib/python3.11/urllib/request.py:563[0m, in [0;36mOpenerDirector.error[0;34m(self, proto, *args)[0m
[1;32m    561[0m [38;5;28;01mif[39;00m http_err:
[1;32m    562[0m     args [38;5;241m=[39m ([38;5;28mdict[39m, [38;5;124m'[39m[38;5;124mdefault[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mhttp_error_default[39m[38;5;124m'[39m) [38;5;241m+[39m orig_args
[0;32m--> 563[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_call_chain([38;5;241m*[39margs)

File [0;32m~/anaconda3/lib/python3.11/urllib/request.py:496[0m, in [0;36mOpenerDirector._call_chain[0;34m(self, chain, kind, meth_name, *args)[0m
[1;32m    494[0m [38;5;28;01mfor[39;00m handler [38;5;129;01min[39;00m handlers:
[1;32m    495[0m     func [38;5;241m=[39m [38;5;28mgetattr[39m(handler, meth_name)
[0;32m--> 496[0m     result [38;5;241m=[39m func([38;5;241m*[39margs)
[1;32m    497[0m     [38;5;28;01mif[39;00m result [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    498[0m         [38;5;28;01mreturn[39;00m result

File [0;32m~/anaconda3/lib/python3.11/urllib/request.py:643[0m, in [0;36mHTTPDefaultErrorHandler.http_error_default[0;34m(self, req, fp, code, msg, hdrs)[0m
[1;32m    642[0m [38;5;28;01mdef[39;00m [38;5;21mhttp_error_default[39m([38;5;28mself[39m, req, fp, code, msg, hdrs):
[0;32m--> 643[0m     [38;5;28;01mraise[39;00m HTTPError(req[38;5;241m.[39mfull_url, code, msg, hdrs, fp)

[0;31mHTTPError[0m: HTTP Error 404: Not Found

